version: "3.8"

services:
  netdata:
    container_name: netdata
    image: netdata/netdata:stable
    restart: unless-stopped
    hostname: thedarkurge
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf:ro
    ports:
      - "19999:19999"
    networks:
      - monitoring_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netdata.rule=Host(`monitor.${DOMAIN}`) || Host(`${TAILSCALE_IP}`)"
      - "traefik.http.routers.netdata.entrypoints=websecure"
      - "traefik.http.routers.netdata.service=netdata"
      - "traefik.http.routers.netdata.tls=true"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  monitoring_net:
    external: true
