version: "3.8"

services:
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /DATA/AppData/prowlarr/config:/config
    ports:
      - "9696:9696"
    networks:
      - media_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`) || Host(`${TAILSCALE_IP}`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.service=prowlarr"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  media_net:
    external: true
