version: '3.8'

services:
  tautulli:
    image: linuxserver/tautulli:2.13.2
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /DATA/AppData/tautulli/config:/config
    networks:
      - media_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 128M
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.tautulli.rule=Host(`tautulli.thedarkurge.li-rattlesnake.ts.net`) || Host(`100.70.106.23`)'
      - "traefik.http.routers.tautulli.entrypoints=websecure"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.routers.tautulli.service=tautulli"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"

networks:
  media_net:
    external: true
