version: '3.8'

services:
  readarr:
    image: linuxserver/readarr:0.3.10-develop
    container_name: readarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /DATA/AppData/readarr/config:/config
      - /mnt/Data/Books:/books
      - /DATA/Downloads:/downloads
    networks:
      - media_net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.readarr.rule=Host(`readarr.thedarkurge.li-rattlesnake.ts.net`) || Host(`100.70.106.23`)'
      - "traefik.http.routers.readarr.entrypoints=websecure"
      - "traefik.http.routers.readarr.tls=true"
      - "traefik.http.routers.readarr.service=readarr"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787"

networks:
  media_net:
    external: true
