version: '3.8'
services:
  traefik:
    container_name: traefik
    image: traefik:v3.0
    restart: unless-stopped
    env_file:
    - .env
    ports:
    - 100.70.106.23:8080:80
    - 100.70.106.23:8443:443
    - 100.70.106.23:9080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./traefik.yml:/traefik.yml:ro
    - ./dynamic-config.yml:/dynamic-config.yml:ro
    - ./acme.json:/acme.json
    - ./thedarkurge.li-rattlesnake.ts.net.crt:/certs/thedarkurge.li-rattlesnake.ts.net.crt:ro
    - ./thedarkurge.li-rattlesnake.ts.net.key:/certs/thedarkurge.li-rattlesnake.ts.net.key:ro
    networks:
    - services_net
    - media_net
    - gaming_net
    - monitoring_net
    labels:
    - traefik.enable=true
    - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)
    - traefik.http.routers.dashboard.service=api@internal
    - traefik.http.routers.dashboard.entrypoints=websecure
    - traefik.http.routers.dashboard.middlewares=auth
    - traefik.http.middlewares.auth.basicauth.users=${DASHBOARD_USER}
    - casaos=casaos
    - custom_id=9db0b1d7-4881-40d3-a1e2-177e3b9a78d2
    - origin=local
    - name=traefik
    - desc=Modern HTTP reverse proxy and load balancer
    - protocol=http
    - show_env=casaos
    - io.casaos.v1.app.store.id=0
    - icon=https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Traefik/icon.png
    - web=8080
    - host=100.70.106.23:8080
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
networks:
  services_net:
    external: true
  media_net:
    external: true
  gaming_net:
    external: true
  monitoring_net:
    external: true
x-casaos:
  store_app_id: traefik
  title:
    en_us: Traefik
  main: traefik
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Traefik/icon.png
  port_map: '9080'
  scheme: http
  index: /
  is_uncontrolled: false
