# Dynamic configuration for Tailscale certificates

tls:
  certificates:
    - certFile: /certs/thedarkurge.li-rattlesnake.ts.net.crt
      keyFile: /certs/thedarkurge.li-rattlesnake.ts.net.key
  
  stores:
    default:
      defaultCertificate:
        certFile: /certs/thedarkurge.li-rattlesnake.ts.net.crt
        keyFile: /certs/thedarkurge.li-rattlesnake.ts.net.key

# Security headers middleware
http:
  middlewares:
    secure-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
