---
- Network:
    - ISP Router:
        - icon: router.png
          href: http://172.26.1.1
          description: Internet Provider Router
    - DD-WRT Router:
        - icon: router.png
          href: http://172.26.1.2
          description: DD-WRT Router

- External:
    - GitHub:
        - icon: github.png
          href: https://github.com/eduard-lt/homelab
          description: Homelab Repo
