---
- Media:
    - Plex:
        icon: plex.png
        href: http://172.26.1.31:32400
        description: Media Server

    - Sonarr:
        icon: sonarr.png
        href: http://172.26.1.31:8989
        description: TV Shows

    - Radarr:
        icon: radarr.png
        href: http://172.26.1.31:7878
        description: Movies

    - Lidarr:
        icon: lidarr.png
        href: http://172.26.1.31:8686
        description: Music

    - Readarr:
        icon: readarr.png
        href: http://172.26.1.31:8787
        description: Books

    - Overseerr:
        icon: overseerr.png
        href: http://172.26.1.31:5055
        description: Requests

    - Tautulli:
        icon: tautulli.png
        href: http://172.26.1.31:8181
        description: Plex Stats

- Downloads:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://172.26.1.31:8081
        description: Torrents

    - Prowlarr:
        icon: prowlarr.png
        href: http://172.26.1.31:9696
        description: Indexers

- Monitoring:
    - Traefik:
        icon: traefik.png
        href: https://100.70.106.23:8443
        description: Reverse Proxy

    - Portainer:
        icon: portainer.png
        href: http://172.26.1.31:9443
        description: Containers

    - Homarr:
        icon: homarr.png
        href: http://172.26.1.31:7575
        description: Dashboard Test
