---
- logo:
    icon: https://gethomepage.dev/img/logo.png

- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false

- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    uptime: true
    units: metric
    refresh: 3000
    label: System (/)

- resources:
    label: Data Storage
    disk: /DATA
    units: metric
    refresh: 5000

- openmeteo:
    label: Brașov
    latitude: 45.6525
    longitude: 25.6069
    timezone: Europe/Bucharest
    units: metric
    cache: 5
