#!/bin/bash
set -e

DISCORD_WEBHOOK="https://discord.com/api/webhooks/1491141708472385641/qVjC2FhBtnEFEVdxtFhrfaJmu5myEbj_47omWfgiYRgOs_Jk2fFjjgHu4p7qMxm4UPOW"

echo "🎬 Setting up Overseerr Discord Notifications..."
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1. Access Overseerr: https://100.70.106.23:8443 (select Overseerr route)"
echo "2. Login to Overseerr"
echo "3. Go to: Settings (⚙️) → Notifications → Discord"
echo "4. Click 'Add Discord Agent'"
echo "5. Configure:"
echo "   - Enable Agent: ✅"
echo "   - Agent Type: Discord"
echo "   - Webhook URL: $DISCORD_WEBHOOK"
echo "   - Username: Overseerr (optional)"
echo ""
echo "6. Select notification types:"
echo "   ✅ Media Requested"
echo "   ✅ Media Auto-Approved"
echo "   ✅ Media Approved"
echo "   ✅ Media Available"
echo "   ✅ Media Failed"
echo "   ✅ Test Notification"
echo "   ✅ Issue Created"
echo "   ✅ Issue Comment"
echo "   ✅ Issue Resolved"
echo ""
echo "7. Click 'Test' to verify"
echo "8. Save Settings"
echo ""
echo "🎉 You'll now get notifications for all media requests!"

