version: '3.8'

services:
  overseerr:
    image: linuxserver/overseerr:1.33.2
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /DATA/AppData/overseerr/config:/config
      - /mnt/Data/Plex/Movies:/movies
      - /mnt/Data/Plex/TV:/tv
    networks:
      - media_net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.overseerr.rule=Host(`overseerr.thedarkurge.li-rattlesnake.ts.net`) || Host(`100.70.106.23`)'
      - "traefik.http.routers.overseerr.entrypoints=websecure"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.routers.overseerr.service=overseerr"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"

networks:
  media_net:
    external: true
