version: '3.8'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./appdata:/appdata
    environment:
      - TZ=Europe/Amsterdam
      - SECRET_ENCRYPTION_KEY=b79db3071ea50afc6aea479a45523254fca7b158993d07c9d7f736c414d00962
      - BASE_URL=http://172.26.1.31:7575
    ports:
      - "7575:7575"
    networks:
      - services_net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.homarr.rule=Host(`homarr.thedarkurge.li-rattlesnake.ts.net`) || Host(`100.70.106.23`)'
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - "traefik.http.routers.homarr.tls=true"
      - "traefik.http.routers.homarr.service=homarr"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
      - "traefik.http.routers.homarr.priority=100"

networks:
  services_net:
    external: true
