version: '3.8'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
      - ./data:/data
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - services_net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.homarr.rule=Host(`homarr.thedarkurge.li-rattlesnake.ts.net`) || Host(`100.70.106.23`)'
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - "traefik.http.routers.homarr.tls=true"
      - "traefik.http.routers.homarr.service=homarr"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
      - "traefik.http.routers.homarr.priority=100"

networks:
  services_net:
    external: true
