version: "3.8"

services:
  vrising:
    container_name: vrising
    image: trueosiris/vrising
    env_file:
      - .env
    volumes:
      - /mnt/Data/Vrising_crack/VRising_Server:/mnt/vrising/server
      - /mnt/Data/Vrising_crack/data:/mnt/vrising/persistentdata
    ports:
      - "9876:9876/udp"
      - "9877:9877/udp"
    restart: unless-stopped
    networks:
      - gaming_net

networks:
  gaming_net:
    name: gaming_net
    driver: bridge
